### ISSUE TITLE
Scraped data not getting stored into a database

### ISSUE THREAD

**Issue by EitvidasPuras** [adriancast/Scrapyd-Django-Template#2]
I'm new to Django and Scrapy. I wrote my code using your code as an example but for some reason the data that I scrape isn't getting saved in a database. From what I understand pipelines are supposed to save everything into a Django model. I want the scraped data to be saved inside a MySQL database that I use for my Django application, but for some reason it's not happening. Am I missing something?

**Comment by adriancast** [comment]
Hi @EitvidasPuras , if you need a detailed guide of how to use this repo you should check this issue: https://github.com/adriancast/Scrapyd-Django-Template/issues/1

Cheerz
