### ISSUE TITLE
scrapyd cant find spider

### ISSUE THREAD

**Issue by oktayozkan0** [adriancast/Scrapyd-Django-Template#28]
i guess this repo is dead but anyways i will try to getting help.

when i send a post request to: 
`http://127.0.0.1:6800/schedule.json?project=scrapy_app&spider=toscrape-css`

response is:
```
{
    "status": "error",
    "message": "spider 'toscrape-css' not found"
}
```

i did a research and i found people talks about "eggifying" but there is no enough information about that in documentation in this repo. how can i solve this issue?

**Comment by adriancast** [comment]
Hello @oktayozkan0,

you can find a detailed guide of how to use this in #1 . Hopefully you are able to follow the guide and run the code 👍🏼

**Comment by adriancast** [comment]
I am going to close the issue, if you are not able to run the code with the guide from #1 feel free to reopen the issue!
